version: '3'

services:
  database:
    image: 'postgres:16'
    restart: unless-stopped
    expose:
      - 5432
    volumes:
      - database:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  bot:
    build: .
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - ./.env:/home/node/app/.env:ro
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_URL: ${TELEGRAM_BOT_URL}
      CRONJOB_SCHEDULE: ${CRONJOB_SCHEDULE}

volumes:
  database:
