version: '3'

services:
  database:
    image: 'postgres:16'
    restart: unless-stopped
    expose:
      - 5432
    volumes:
      - database:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - database
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      CRONJOB_SCHEDULE: ${CRONJOB_SCHEDULE}

volumes:
  database:
